# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      - run: npm run qa
      - run: npm run build --if-present
      - run: npm test
      - name: Install Playwright dependencies
        run: npm install
        working-directory: tools/snapshot-tests
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: tools/snapshot-tests
      - name: Run Playwright tests
        run: npm run test
        working-directory: tools/snapshot-tests
        env:
          PLAYWRIGHT_START_SERVER: "true"
          PLAYWRIGHT_PORT: "5173"
          PLAYWRIGHT_HOST: "localhost"
